const Products = [
    {id:1, name:"Lightweight Jacket", price:"32000", img:"product-01.jpg", imgDetail1:"product-detail-01.jpg", imgDetail2:"product-detail-02.jpg", imgDetail3:"product-detail-03.jpg", description:"Nulla eget sem vitae eros pharetra viverra. Nam vitae luctus ligula. Mauris consequat ornare feugiat.", category:"men", stock: 10},
    {id:2, name:"Herschel supply", price:"8500", img:"product-02.jpg", imgDetail1:"product-detail-01.jpg", imgDetail2:"product-detail-02.jpg", imgDetail3:"product-detail-03.jpg", description:"Nulla eget sem vitae eros pharetra viverra. Nam vitae luctus ligula. Mauris consequat ornare feugiat", category:"women", stock: 10},
    {id:3, name:"Only Check Trouser", price:"52000", img:"product-03.jpg", imgDetail1:"product-detail-01.jpg", imgDetail2:"product-detail-02.jpg", imgDetail3:"product-detail-03.jpg", description:"Nulla eget sem vitae eros pharetra viverra. Nam vitae luctus ligula. Mauris consequat ornare feugiat.", category:"men", stock: 10},
    {id:4, name:"Classic Trench Coat", price:"125000", img:"product-04.jpg", imgDetail1:"product-detail-01.jpg", imgDetail2:"product-detail-02.jpg", imgDetail3:"product-detail-03.jpg", description:"Nulla eget sem vitae eros pharetra viverra. Nam vitae luctus ligula. Mauris consequat ornare feugiat", category:"women", stock: 10},
    {id:5, name:"Lightweight Jacket", price:"32000", img:"product-01.jpg", imgDetail1:"product-detail-01.jpg", imgDetail2:"product-detail-02.jpg", imgDetail3:"product-detail-03.jpg", description:"Nulla eget sem vitae eros pharetra viverra. Nam vitae luctus ligula. Mauris consequat ornare feugiat.", category:"men", stock: 10},
    {id:6, name:"Herschel supply", price:"8500", img:"product-02.jpg", imgDetail1:"product-detail-01.jpg", imgDetail2:"product-detail-02.jpg", imgDetail3:"product-detail-03.jpg", description:"Nulla eget sem vitae eros pharetra viverra. Nam vitae luctus ligula. Mauris consequat ornare feugiat", category:"women", stock: 10},
    {id:7, name:"Only Check Trouser", price:"52000", img:"product-03.jpg", imgDetail1:"product-detail-01.jpg", imgDetail2:"product-detail-02.jpg", imgDetail3:"product-detail-03.jpg", description:"Nulla eget sem vitae eros pharetra viverra. Nam vitae luctus ligula. Mauris consequat ornare feugiat.", category:"men", stock: 10},
    {id:8, name:"Classic Trench Coat", price:"125000", img:"roduct-04.jpg", imgDetail1:"product-detail-01.jpg", imgDetail2:"product-detail-02.jpg", imgDetail3:"product-detail-03.jpg", description:"Nulla eget sem vitae eros pharetra viverra. Nam vitae luctus ligula. Mauris consequat ornare feugiat", category:"women", stock: 10}
];

export default Products;